name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build and Test Rust Projects
        run: |
          cd consensus && cargo build && cargo test
          cd ../evm && cargo build && cargo test
          cd ../bridge && cargo build && cargo test

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: Build and Test Go API
        run: |
          cd api && go build ./... && go test ./...
