name: CI

on:
  push:
    branches:
      - dev
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build & Test Rust Modules
        run: |
          cd consensus && cargo build && cargo test
          cd ../evm && cargo build && cargo test
          cd ../bridge && cargo build && cargo test

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.19"

      - name: Build & Test Go API
        run: |
          cd api && go build ./... && go test ./...
